---
- name: Transfer and execute a script.
  hosts: dbservers
  tasks:
     - name: Transfer the script
       copy: src=/tmp/test.sh dest=/tmp mode=0777

     - name: Execute the script
       command: sh /tmp/test.sh
